### PR TITLE
fix #5, fix tmp files overlap

### LINKED ISSUE #5: Static /tmp files leading to surpising effects
## Current Behavior
http-gw (and likely others) role saves a file with neofs-http-gw binary into /tmp/neofs-http-gw-linux-amd64 and leaves it after the exit which leads to the following:
 * version upgrades are no longer possible to perform from the same host until this file is deleted
 * any previously-existing garbage file can be used instead of a proper binary
 * other processes can do something with the same static name
 * some disk space is used without any real reason

## Expected Behavior
Some private tmp space should be used for a particular play/role run, it should be cleaned up after the use.

### PR DESCRIPTION
**Pull request by 532910**

### CODE REVIEW

**Review by roman-khimov — COMMENTED** [review]
Can we use `mktemp`? Can this file be deleted on exit?

**Comment by 532910** [comment]
Not sure. And definitely not this pr and this issue. Open a new one if you'd like.

**Comment by roman-khimov** [comment]
It's absolutely the same issue that we need a better solution for.

**Comment by 532910** [comment]
this issue is about side effects and this pr fixes it

**Comment by roman-khimov** [comment]
Please, reread #5. This solves "version upgrades are no longer possible to perform from the same host until this file is deleted" part of it. Nice. Far from perfect.

**Review by roman-khimov — APPROVED** [review]
No better solution for now, unfortunately.

**Pull request merged**
